INSERT INTO T_SIP_DEPARTAMENTO(CD_DEPARTAMENTO, NM_DEPARTAMENTO, SG_DEPARTAMENTO)
    VALUES (1, 'FINANCEIRO', 'FIN');
    
INSERT INTO T_SIP_DEPARTAMENTO(CD_DEPARTAMENTO, NM_DEPARTAMENTO, SG_DEPARTAMENTO)
    VALUES (2, 'TECNOLOGIA DA INFORMAÇÃO', 'TIN');
    
--NÃO PRECISA SABER DA FORMATACAO
--- PORÉM PRECISA SER OBROGATÓRIA DA FUNÇÃO TO_DATE()
INSERT INTO T_SIP_FUNCIONARIO
    VALUES (12345,
            2, 
            'TALITA MOURA', 
            TO_DATE('19/02/1999', 'DD/MM/YYYY'), 
            TO_DATE('09/07/2020', 'DD/MM/YYYY'), 
            ' Rua das Margaridas, São Paulo - SP', 
            1900.85 );
             -- VALOR DECIMAL: 0000.00 ("." COMO VÍRGULA PARA VALORES)
   
INSERT INTO T_SIP_PROJETO
VALUES(1,
        'PROJETO TIN',
        TO_DATE('11/02/2022', 'DD/MM/YYYY'), '');
   
   
    
--COMANDO: SQL -> DQL/DRS
----------------- DATA QUERY/RETRIEVE LANGUAGE
SELECT * FROM T_SIP_PROJETO;
-- TODAS AS COLUNAS E LINHAS DA TABELA

SELECT DISTINCT NM_DEPARTAMENTO FROM T_SIP_DEPARTAMENTO;


